export const JOBS = [
  { label: "Artisan", value: 1 },
  { label: "Chauffeur particulier", value: 2 },
  { label: "Chauffeur Taxi", value: 3 },
  { label: "Chauffeur Taxibe", value: 4 },
  { label: "Chauffeur Taxibrousse", value: 5 },
  { label: "Chercheur", value: 6 },
  { label: "Commissaire", value: 7 },
  { label: "Comptable", value: 8 },
  { label: "Coursier", value: 9 },
  { label: "Directeur", value: 10 },
  { label: "Docteur", value: 11 },
  { label: "Facteur", value: 12 },
  { label: "Gardien", value: 13 },
  { label: "Geometre", value: 14 },
  { label: "Greffier", value: 15 },
  { label: "Infirmier", value: 16 },
  { label: "Informaticien", value: 17 },
  { label: "Inspecteur", value: 18 },
  { label: "Maçon", value: 19 },
  { label: "Mécanicien", value: 20 },
  { label: "Militaire", value: 21 },
  { label: "Balayeur", value: 22 },
  { label: "Femme de ménage", value: 23 },
  { label: "Agriculteur", value: 24 },
  { label: "Enseignant(e)", value: 25 },
  { label: "Réparateur de pneus", value: 26 },
  { label: "Coordonier", value: 27 },
  { label: "Coiffeur(se)", value: 28 },
  { label: "Jardinier(e)", value: 29 },
  { label: "Lessiveur(se)", value: 30 },
  { label: "Agent de propreté de la commune", value: 31 },
  { label: "Couturier", value: 32 },
  { label: "Pêcheur", value: 33 },
  { label: "Etudiant", value: 34 },
  { label: "Auxiliaire de maison", value: 35 },
  { label: "Mpiompy", value: 36 },
  { label: "Avocat", value: 37 },
  { label: "Pasteur", value: 38 },
  { label: "Tireur de pousse pousse", value: 39 },
  { label: "Tireur de charette", value: 40 },
  { label: "Juge", value: 41 },
  { label: "Prostituée", value: 42 },
  { label: "Marchand(e)", value: 43 },
  { label: "Opérateur de saisie", value: 44 },
  { label: "Planton", value: 45 },
  { label: "Professeur", value: 46 },
  { label: "Receveur taxibe", value: 47 },
  { label: "Sagefemme", value: 48 },
  { label: "Sécurité", value: 49 },
  { label: "Secrétaire", value: 50 },
  { label: "Chômeur(se)", value: 51 },
  { label: "Autres", value: 52 },
  { label: "Ne travail pas", value: 53 },
]

export const OTHER_JOB_ID = 52
